require'nvim-treesitter.configs'.setup {
  ensure_installed = { 
      "c",
      "lua",
      "vim",
      "help",
      "cpp",
      "rust",
      "markdown",
      "markdown_inline",
      "svelte",
      "graphql",
      "bash",
      "lua",
      "vim",
      "dockerfile",
      "gitignore",
      "json",
      "yaml",
  },
  sync_install = false,
  auto_install = true,
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
}
